export const metadata = {
  title: "Home Page",
  description: "Home Desc Generated by create next app",
  alternates: {
    canonical: "https://www.example.com/",
  },
};


function Home() {
  return (
    <div>Home</div>
  )
}

export default Home